// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJS9QhqDJaqnXTAsJ3nzVKQ67lE5RLW4',
    appId: '1:922389522549:web:56b67ec4d0ddb16678f03c',
    messagingSenderId: '922389522549',
    projectId: 'tectone23-97468',
    authDomain: 'tectone23-97468.firebaseapp.com',
    storageBucket: 'tectone23-97468.appspot.com',
    measurementId: 'G-NRSFC3GQMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA345VZBWq1pjNFI-oyTrC6zhQc8-uTVSg',
    appId: '1:922389522549:android:683cef98d0ea4e6778f03c',
    messagingSenderId: '922389522549',
    projectId: 'tectone23-97468',
    storageBucket: 'tectone23-97468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExSze3VsguBCwJW36YILQ3Zv9uZHegxc',
    appId: '1:922389522549:ios:c34cba98f72e10d978f03c',
    messagingSenderId: '922389522549',
    projectId: 'tectone23-97468',
    storageBucket: 'tectone23-97468.appspot.com',
    iosBundleId: 'com.example.tectone23Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExSze3VsguBCwJW36YILQ3Zv9uZHegxc',
    appId: '1:922389522549:ios:0e8b71cb0acf34f978f03c',
    messagingSenderId: '922389522549',
    projectId: 'tectone23-97468',
    storageBucket: 'tectone23-97468.appspot.com',
    iosBundleId: 'com.example.tectone23Test.RunnerTests',
  );
}
